/* eslint-disable */
_w['_sydBaseSpecifierPrefix'] = 'rms-answers-SharedStaticAssets-';
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableBackgroundFix: true,
  usePill: true,
  enableSydTigerAns: true,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  sydOptionSets: 'spktxtibmoff,uquopt,enelecintl,gndeleccf,gndlogcf,jbfv203,2tlocretbn,osbsdrecoff',
  sydBalOpts: 'cgptrsndlwcp,flxclmdlspwcp,gldcl1wcp,glfluxv15wcp,invocmax',
  sydCrtOpts: 'invocmax',
  sydPrcOpts: 'invocmax',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs: 'gbacf,bggrey,1366cf,multlingcf,stibmoff,tts4,ttsvivn,caccnctacf,specedge,inosanewsmob,wrapnoins,racf,rwt2,dismmaslp,1117gndelecs0,713logprobss0,1111jbfv203,1118wcpdcl,117invocmax,10312tlocret,1025gptv_v2s0,fluxnosearch,1115fluxvs0,727nrprdrt6,727nrprdrt5,codecreator1,cacmuidarb,edgenorrwrap,tstchtadd',
  sydBaseUrl: location.origin,
  compSydRequestSource: 'cib',
  compSydRequestScenario: 'chat',
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  enableSapphireSydVoiceExp: true,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  timezoneoffset: '8',
  lat: '78.4156',
  long: '-101.4458',
  language: 'Vietnamese (Vietnam)',
  userMailId: randomString(Math.round(Math.random()*16))+'@'+randomLowercaseString(randomString(Math.round(Math.random()*12)))+'.com',
  username: randomString(Math.round(Math.random()*16)),
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  moveOnlySydXAnswers: true,
  enableSydX1T: true,
  enableSydTestCache: false,
  enableSydCarousel: true,
  traceId: randomLowercaseString(32),
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: true,
  enableSydShare: true,
  enableSydCookLoc: true,
  enableSQMsg: true,
  addDv3Opt: true,
  enableErrorTelemetry: true,
  checkCreatorAnsFor1T: true,
  enableAnsCardSuffix: true,
  isAdultUser: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableDM: true,
  enableSydImageCreate: true,
  enableToneCook: true,
toneDefault: 'Creative',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableAudioPreloadLimit: true,
  enableSpeechFateTTSStop: true,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
// 设置已登录账号的聊天对话次数
  maxTurnsPerConversation: 30,
// 设置未登录账号的聊天对话次数
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableAdSlugsMobile: true,
  enableUnauthRedir: true,
  enableVersionedApiCalls: true,
  enableJWTFTRFix: true,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  enableStreamSyntheticTextResponses: true,
  enableStreamSyntheticTextResponsesForBalancedTone: true,
  enableStreamSyntheticTextResponsesForCreativeTone: true,
  enableStreamSyntheticTextResponsesForPreciseTone: true,
  syntheticStreamSpeed: 55,
  syntheticStreamSpeedForBalancedTone: 55,
  syntheticStreamSpeedForCreativeTone: 55,
  syntheticStreamSpeedForPreciseTone: 55,
  enableMobileShareAnchorBottom: true,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableInlineFeedback: true,
  enableInlineFeedbackV21: true,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  sydSapphireUpsellVisualSearchQRCodeUrl: 'https://bingapp.microsoft.com/bing?adjust=13uz7blz_13evwnmy',
  enableSydneySapphireUpsellMessageActions: true,
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://bingapp.microsoft.com/bing?style=newbing\u0026adjust=euhmno2_oy62nz1',
  enableConvModeSwitchAjax: true,
  enableSetToneFromUrl: true,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  enablePrivacyConsent: true,
  enableFixCodeXAsBug: true,
  enableThreads: true,
  enableSkipContentOriginCheck: true,
  enableMobileOneClickShareV2: true,
  enableDynamicShareTitle: true,
  enableSharePreview: true,
  enableSharedHoverCitations: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableFixOnReplaceAllJSError: true,
  enableShareCurrentThreadMessagesfromAPI: true,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: true,
  enableVisualSearch: true,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  suppressPoleRSWhenEnableSydCarousel: true,
  disablePassBotGreetingInContext: true,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  suppressPoleRecommendedSearchWhenEnableSydCarousel: true,
  enableCopyButtonInstrumented: true,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableMessageExportOnlineExcel: true,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableDirectlyOpenExportOnlineLink: true,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: true,
  enableLimitToAadOnlineExport: true,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableGetChats: true,
  enableDelayGetChats: true,
  enableExportDocxWithFormat: true,
  enableThreadSync: true,
  enableFlux3P: true,
  disableWelcomeScreen: true,
  enableWelcomeScreenV2: true,
  codexTableVersion: true,
  enableBICHistory: true,
  enableRenderCardRequestIMSearchParams: true,
  typingIndicatorAnimationDuration: 1000,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableTypewriter: true,
  fileUploadMaxSizeLongContext: 10000000,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableFaviconsV2: true,
  enableUserIpAddress: true,
  enableActionBarV2: true,
  speechSurface: 'desktop',
  enableKatexScroll: true,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableThreadShowPlugins: true,
  enableUpdateUserMessageId: true,
  enablePluginPanelFre: true,
  enableMobileFirstClickShare: true,
  personalizationInlineConsentTurn: false,
  enableNoBingSearchResponseBackground: true,
  enableNoSearchPluginMetaMessage: true,
  enableInlineAdsDynamicWidth: true,
  enableShareInThreadsHeader: true,
  enableDeleteSingleConversationMemory: true,
  enableStableAutosuggestion: true,
  threadsAutoSaveOptionset: 'autosave',
  enableUserMessageRewriteAndCopy: true,
  enableBCBSensitivityLabel: true,
  enableOneDs: true,
  enablePromptHandling: true,
  dedicatedIpType: 'unknown',
  enableCIQEmail: true,
  enableCIQAutoScoping: true,
  enableCachedContentFixForIsStartOfSession: true,
  extraNotebookOptionsSets: 'iycapbing,iyxapbing,prjupy',
  notebookMaxMessageLength: 18000,
  initialShowConvPresent: true,
  enableAttributionsV2: true,
  minimumZeroInputSuggestionCount: true,
  imageSearchFormCode: 'IACMIR',
  imageSearchEnableMediaCanvas: true,
  imageSearchMaxImageCount: 5,
  imageSearchForceSquareImages: true,
  enableRelativeSignInUrl: true,
  chatBackgroundColorOverride: 'f7f7f8',
  codexOptionsSetsList: [{
    value: 'iyxapbing'
  },
  {
    value: 'iycapbing'
  }],
  autoHideConvInterval: 3600000,
  enableAjaxBundlePLoad: true,
  PLoadIID: 'SERP.5883'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: 'Vui lòng hỏi tôi nếu bạn có bất kỳ câu hỏi nào... (Shift + Enter = dòng mới, "/" kích hoạt từ gợi ý)',
  actionBarAriaLabel: 'Hỏi Bing',
  actionBarComposeButton: 'Chủ đề mới',
  actionBarNewChatButtonDesktop: 'Bắt đầu trò chuyện mới',
  actionBarNewChatButtonMobile: 'cuộc trò chuyện',
  actionBarOngoingConvPlaceholder: 'Gõ tin nhắn',
  attachmentLoading: 'Đang tải phần đính kèm',
  bufferMessage1: 'Tôi đang sử dụng nó, xin vui lòng chờ đợi',
  bufferMessage2: 'Xin vui lòng chờ một chút',
  bufferMessage3: 'Hãy dành một chút thời gian để suy nghĩ ...',
  captchaTitle: 'Xác minh danh tính',
  captchaDescription: 'Để tiếp tục, hãy nhập các ký tự trong hình dưới đây. ',
  captchaPlaceholder: 'Nhập ký tự...',
  captchaPlaceholderError: 'Xin lỗi, vui lòng thử lại. ',
  next: 'Tiếp theo',
  cancel: 'Hủy bỏ',
  feedbackAccessed: 'thời gian truy cập',
  feedbackSource: 'Nguồn: Đối thoại với Bing,',
  feedbackShareConversationQuery: 'Phiên bản mới Bing là gì?',
  messageLearnMore: 'Tìm hiểu thêm:',
  messageReference: 'tham khảo',
  messageReferences: 'trích dẫn',
  messagePrivacyLabel: 'Dữ liệu cá nhân và công ty của bạn được bảo vệ trong cuộc trò chuyện này',
  inputRaiLabel: '',
  letsChat: 'Hãy trò chuyện',
  pause: 'Tạm dừng',
  play: 'Bắt đầu trò chơi',
  speechFailedRecognitionError: 'Xin lỗi, tôi không thể nghe giọng nói của bạn vì máy chủ giọng nói bị tắt, vui lòng thử lại sau. ',
  speechListening: 'Tôi lắng nghe ...',
  speechLoading: 'Đang chờ âm thanh...',
  speechMediaNotReachableError: 'Tôi rất tiếc, tôi không thể nghe giọng nói của bạn vì bạn không có micrô sẵn dùng. ',
  speechNoPermissionError: 'Bạn cần bật micrô trước khi tôi có thể nghe thấy bạn. ',
  speechAudioPlaybackError: 'Đã xảy ra lỗi.',
  stop: 'Dừng',
  welcomeContainerFAQs: 'Câu hỏi thường gặp',
  welcomeContainerPrivacyStatement: 'Riêng tư',
  welcomeContainerUseTerms: 'điều khoản',
  welcomeContainerLearnMore: 'Tìm hiểu thêm',
  welcomeMessageItemContent1: 'Tôi có thể làm gì cho những đứa trẻ mà tôi kén chọn chỉ ăn thức ăn màu cam?',
  welcomeMessageItemContent2: 'Những ưu điểm và nhược điểm của 3 máy hút bụi thú cưng bán chạy nhất là gì?',
  welcomeMessageItemContent3: 'Viết một câu về cá sấu ngoài không gian với giọng điệu của cướp biển',
  welcomeMessageItemTitle1: ' 🧐 Đặt câu hỏi phức tạp',
  welcomeMessageItemTitle2: '🙌 Nhận câu trả lời tốt hơn',
  welcomeMessageItemTitle3: '🎨 Lấy cảm hứng sáng tạo',
  welcomeMessageItemLabel4: 'Nhiều tính năng mới trong sáng tạo:',
  warmWelcomeTitle: 'Chào mừng bạn đến với Bing mới',
  warmWelcomeTitleLine2: '',
  warmWelcomeAriaLabel: 'Chào mừng bạn đến với Bing mới',
  welcomeSubtitleText: 'Trợ lý trực tuyến được HỖ TRỢ AI',
  workToggleDescription: 'và kết quả của bạn bao gồm những gì',
  feedbackFirstMessage: 'Tôi rất tiếc vì đã không giúp bạn. Bạn có thể giải thích chi tiết các khía cạnh bạn không thích không?',
  feedbackPromptMessage: 'Cảm ơn lời nhắc. Vui lòng cung cấp phản hồi để nhóm Bing có thể xem. ',
  feedbackPromptGiveFeedback: 'cung cấp phản hồi',
  feedbackPromptGiveFeedbackAriaLabel: 'cung cấp phản hồi',
  feedbackPromptReportAConcern: 'Báo cáo vấn đề',
  feedbackPromptPositive: 'Vui mừng bạn thích câu trả lời này! ',
  feedbackFormTitleText: 'Tại sao điều này không hoạt động? ',
  feedbackFormInputDefaultText: 'Thêm chi tiết hơn ở đây. Để giúp bảo vệ quyền riêng tư của bạn, vui lòng không điền thông tin cá nhân như tên hoặc địa chỉ email của bạn. ',
  feedbackFormLegalText: 'Có vấn đề pháp lý hoặc chính sách nào không? ',
  feedbackFormReportAConcern: 'Báo cáo vấn đề',
  feedbackFormNotificationTitleText: 'Phản hồi đã được gửi',
  feedbackFormNotificationBodyText: 'Cảm ơn bạn đã giúp Bing cải thiện! ',
  feedbackFormThanksMessage: 'Cảm ơn bạn đã phản hồi của bạn!',
  feedbackFormReturnToChatMessage: 'Quay lại trò chuyện',
  serpFeedbackFormTitleText: 'Hãy giúp chúng tôi cải thiện trải nghiệm',
  serpFeedbackFormInputDefaultText: 'Nhập phản hồi ở đây. Để giúp bảo vệ quyền riêng tư của bạn, vui lòng không điền thông tin cá nhân như tên hoặc địa chỉ email của bạn. ',
  serpFeedbackFormScreenshot: 'bao gồm ảnh chụp màn hình này',
  serpFeedbackFormRadioLike: 'Thích',
  serpFeedbackFormRadioDislike: 'giẫm',
  serpFeedbackFormRadioConnectionIssues: 'Kết nối vấn đề',
  serpFeedbackFormRadioSlowResponses: 'Phản hồi chậm',
  serpFeedbackFormRadioOther: 'Khác',
  feedbackFormUnderstandDataSharedText: 'Tìm hiểu thêm về nội dung được chia sẻ dưới dạng dữ liệu chẩn đoán',
  feedbackFormUserConsentText: 'Chia sẻ lời nhắc với Copilot, phản hồi nhận được từ Copilot và dữ liệu chẩn đoán cho tương tác này?',
  feedbackFormUserConsentYesText: 'Có',
  feedbackFormUserConsentNoText: 'Không',
  feedbackFormPrivacyStatement: 'Tuyên bố về quyền riêng tư',
  feedbackFormPrivacyText: 'Sau khi Gửi phản hồi của bạn sẽ được sử dụng để cải thiện các sản phẩm và dịch vụ của Microsoft. Quản trị viên CNTT của tổ chức sẽ có thể xem và quản lý dữ liệu phản hồi.',
  compliantPositiveFeedbackFormTitleText: 'Gửi phản hồi cho Microsoft',
  compliantPositiveFeedbackQuestionText: 'Bạn thích những khía cạnh nào?',
  compliantPositiveFeedbackDefaultText: 'Vui lòng không cung cấp bất kỳ thông tin cá nhân nào. ',
  compliantNegativeFeedbackFormTitleText: 'Gửi phản hồi chi tiết đến Microsoft',
  compliantNegativeFeedbackCategoryText: 'Nội dung này là',
  compliantNegativeFeedbackQuestionText: 'Có chuyện gì vậy?',
  compliantFeedbackThanksText: 'Cảm ơn bạn đã gửi phản hồi về {0}!',
  compliantFeedbackCategoryInaccurate: 'không chính xác',
  compliantFeedbackCategoryOffensive: 'xúc phạm hoặc không phù hợp',
  compliantFeedbackCategoryOther: 'Khác',
  submit: 'Gửi',
  explore: 'Duyệt',
  exploreMore: 'Duyệt thêm',
  metaInternalSearchQuery: 'Đang tìm kiếm: `{0}`',
  metaInternalLoaderMessage: 'Đang tạo ra câu trả lời cho bạn ...',
  metaInternalImageLoaderMessage: 'Phân tích hình ảnh: Sự mơ hồ về quyền riêng tư sẽ ẩn khuôn mặt trong cuộc trò chuyện Bing',
  compliantMetaInternalLoaderMessage: 'Tạo câu trả lời bảo mật từ {0}',
  messageSharedContent: 'Chia sẻ nội dung',
  clickToView: 'Nhấp để xem',
  more: 'Nhiều hơn',
  expand: 'Mở',
  welcomeTertiaryTitleText: 'Sử dụng sức mạnh của AI để tìm câu trả lời từ web, tạo nội dung bằng văn bản và hơn thế nữa. ',
  actionBarTextInputAriaLabel: 'Hỏi Bing',
  seeMore: 'Xem thêm',
  seeLess: 'Xem ít hơn',
  raiSuggestions: 'Đây là gì?',
  actionBarFileUploadButtonAriaLabel: 'Tìm kiếm trong tệp',
  actionBarStopStreamingAriaLabel: 'Ngừng phát trực tuyến',
  actionBarTextInputModeButtonAriaLabel: 'Sử dụng bàn phím',
  actionBarSpeechInputModeButtonAriaLabel: 'Sử dụng micrô',
  actionBarVisualSearchButtonTooltip: 'Thêm hình ảnh',
  actionBarVisualSearchButtonAriaLabel: 'Thêm hình ảnh bạn muốn tìm kiếm',
  actionBarVisualSearchCoachMarkTitle: 'Bing mới với hình ảnh',
  actionBarVisualSearchCoachMarkDescription: 'Bây giờ bạn có thể sử dụng hình ảnh để trò chuyện với Bing! ',
  actionBarVisualSearchCoachMarkImgAlt: 'Hình ảnh gợi ý công cụ tìm kiếm trực quan',
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: 'Hủy đầu vào giọng nói / đọc ra',
  actionBarEditModeButtonAriaLabel: '固定',
  actionBarSpeechBtnStartListeningAriaLabel: 'Sử dụng micrô',
  actionBarSpeechBtnStopListeningAriaLabel: 'Ngừng nghe',
  actionBarSpeechBtnStopReadoutAriaLabel: 'Ngừng đọc ra',
  feedbackLikeButtonAriaLabel: 'Thích',
  feedbackDislikeButtonAriaLabel: 'Không thích',
  feedbackOffensiveButtonAriaLabel: 'đánh dấu là xúc phạm',
  feedbackCopyButtonAriaLabel: 'Sao',
  feedbackShareButtonAriaLabel: 'Chia',
  messageSentAriaLabelPrefix: 'Đã gửi email',
  messageReceivedAriaLabelPrefix: 'Đã nhận được tin nhắn',
  messageAttributionsCollapseBtnAriaLabel: 'Gấp',
  newTopicGreet1: 'Cảm ơn bạn! Nó luôn luôn hữu ích để biết khi nào bạn đã sẵn sàng để di chuyển trên. Tôi có thể trả lời những câu hỏi nào cho bạn bây giờ?',
  newTopicGreet2: 'Nó luôn luôn là tuyệt vời để bắt đầu lại. Hỏi tôi bất kỳ câu hỏi nào!',
  newTopicGreet3: 'Tất nhiên, tôi rất muốn bắt đầu lại. Tôi có thể giúp gì cho bạn bây giờ?',
  newTopicGreet4: 'Tất nhiên, tôi đã sẵn sàng cho những thách thức mới. Tôi có thể làm gì cho bạn bây giờ?',
  newTopicGreet5: 'Vâng, chúng ta hãy thay đổi chủ đề. Anh đang nghĩ gì vậy?',
  newTopicGreet6: 'Đừng lo lắng, tôi rất vui khi thử một cái gì đó mới. Tôi có thể trả lời những câu hỏi nào cho bạn bây giờ?',
  newTopicGreet7: 'Ok, tôi đã sẵn sàng! Cảm ơn bạn đã thiết lập lại. Chúng ta nên biết gì? ',
  newTopicGreet8: 'Cảm ơn bạn đã làm mới! Bạn có một chủ đề mới? ',
  newTopicGreet9: 'Hiểu rồi, chúng ta hãy bắt đầu lại từ đầu. Tôi nên thảo luận về điều gì tiếp theo? ',
  newTopicGreet10: 'Tiếp theo! Tôi có thể giúp gì cho anh? ',
  newTopicGreet11: 'Ok, tôi đã sẵn sàng cho một chủ đề mới. Chúng ta nên cùng nhau tìm hiểu những gì? ',
  newTopicGreet12: 'Hiểu rồi, xin vui lòng tiếp tục! Cảm ơn bạn đã cho tôi biết. Tôi có thể giúp gì? ',
  newTopicSugg1: 'Dạy cho tôi một từ mới',
  newTopicSugg2: 'Làm thế nào để đặt ra các mục tiêu có thể đạt được?',
  newTopicSugg3: 'Dạy tôi thông tin về cuộc đổ bộ mặt trăng',
  newTopicSugg4: 'Động vật có vú nhỏ nhất thế giới là gì?',
  newTopicSugg5: 'Đại dương sâu nhất là cái nào?',
  newTopicSugg6: 'Có bao nhiêu giờ một năm?',
  newTopicSugg7: 'Tôi muốn học một kỹ năng mới',
  newTopicSugg8: 'Hãy để tôi cười',
  newTopicSugg9: 'Có tin gì không?',
  newTopicSugg10: 'Hãy cho tôi thấy những câu nói truyền cảm hứng',
  newTopicSugg11: 'Hãy cho tôi một trò đùa',
  newTopicSugg12: 'Tôi cần trợ giúp về bài tập về nhà',
  newTopicSugg13: 'Tìm kiếm các tác phẩm không hư cấu',
  newTopicSugg14: 'Truyền cảm hứng cho tôi!',
  newTopicSugg15: 'Hiển thị công thức nấu ăn cho tôi',
  newTopicSugg16: 'Làm thế nào để tạo ngân sách?',
  newTopicSugg17: 'Dạy cho tôi một từ mới',
  newTopicSugg18: 'Thời tiết như thế nào?',
  newTopicSugg19: 'Tôi muốn học một kỹ năng mới',
  newTopicSugg20: 'Vũ trụ bắt đầu như thế nào?',
  newTopicSugg21: 'Tại sao con người cần ngủ?',
  newTopicSugg22: 'Làm thế nào để làm cho bánh?',
  newTopicSugg23: 'Tại sao hồng hạc là màu hồng?',
  newTopicSugg24: 'Hình ba chiều hoạt động như thế nào?',
  newTopicSugg25: 'Kim tự tháp được xây dựng như thế nào?',
  newUserGreet: 'Chào mừng! Tôi là Bing và tôi có thể sử dụng AI để hoàn thành nhiều công việc như giúp bạn tìm thấy món quà hoàn hảo, tìm hiểu về đại dương hoặc khám phá âm nhạc mới. Cho tôi biết những gì bạn muốn biết! ',
  newUserSugg1: 'Viết một bài hát',
  newUserSugg2: 'Chơi kéo đá vải',
  newUserSugg3: 'Tìm kiếm trang web',
  repeatUserGreet: 'Rất vui được gặp lại bạn! Hãy tiếp tục cuộc trò chuyện. Anh thế nào rồi? ',
  repeatUserSugg1: 'Chơi trò chơi nhỏ',
  repeatUserSugg2: 'Đề nghị một cuốn sách hay',
  repeatUserSugg3: 'Hãy cho tôi biết một câu đố',
  creativeGreet: 'Tốt! Nó sẽ được vui vẻ. Anh đang nghĩ gì vậy? ',
  balancedGreet: 'Ok, chúng ta hãy tìm câu trả lời và nói chuyện với ngày. Tôi có thể giúp gì cho anh? ',
  preciseGreet: 'Cảm ơn trò chuyện. Hôm nay tôi có thể giúp gì cho anh? ',
  creativeSugg1: 'Hãy cho tôi biết chòm sao',
  creativeSugg2: 'Hãy cho tôi một câu hỏi bạn muốn hỏi',
  creativeSugg3: 'Viết một bức thư tình cho Giông bão',
  balancedSugg1: 'Viết một bài thơ về bỏng ngô',
  balancedSugg2: 'Các ngôi sao có thể được nhìn thấy ở đâu gần đó?',
  balancedSugg3: 'Tôi cần một số lời khuyên',
  preciseSugg1: 'Tôi cần giúp đỡ để làm nghiên cứu',
  preciseSugg2: 'Nhật thực tiếp theo là khi nào',
  preciseSugg3: 'Hãy cho tôi biết tổng thống thứ 22',
  close: 'Tắt',
  newTopicPrompt: 'Với các chủ đề mới, bạn có thể bắt đầu một cuộc trò chuyện hoàn toàn mới với Bing về bất kỳ chủ đề nào',
  typingIndicatorStopRespondingAriaLabel: 'Ngừng phản hồi',
  loading: 'Đang tải',
  canceling: 'Đang hủy bỏ',
  welcomeLearnSegment0: 'Bing được hỗ trợ bởi AI, vì vậy có thể có tai nạn và lỗi. Hãy chắc chắn rằng bạn kiểm tra các sự kiện, và',
  welcomeLearnSegment1: 'Chúng ta hãy học cùng nhau.Bing được hỗ trợ bởi AI, vì vậy tai nạn và lỗi có thể xảy ra. Hãy chắc chắn rằng bạn kiểm tra các sự kiện, và',
  welcomeLearnSegment2: 'Chia sẻ phản hồi',
  welcomeLearnSegment3: 'Để chúng tôi có thể tìm hiểu và cải thiện!',
  welcomeLearnMessage: 'Bing được hỗ trợ bởi AI, vì vậy tai nạn và lỗi có thể xảy ra. Xin vui lòng chia sẻ phản hồi để chúng tôi có thể cải thiện!',
  welcomeLearnMessage2: 'Bing Chat xử lý các từ bạn nhập vào Windows Copilot để tạo phản hồi dựa trên AI và cải thiện trải nghiệm của bạn trong Windows. ',
  welcomeLearnFeedbackSubstitute: 'Chia sẻ phản hồi',
  adsDisclaimer: 'Quảng cáo không phải là mục tiêu dựa trên nhận dạng không gian làm việc hoặc lịch sử trò chuyện. {0}。 ',
  adsDisclaimerMobileTitle: null,
  adsDisclaimerLearnMoreLink: 'Hơn nữa nhiều',
  actionBarSuspendConvPlaceHolder: 'Nhắn tin đã bị vô hiệu hóa cho tài khoản đang chờ',
  actionBarNewlineTooltip: 'Sử dụng Shift+Enter để tạo ngắt dòng cho tin nhắn dài hơn',
  notiReConnect: 'Lỗi rồi. ',
  notiChatEnd: 'Chủ đề trò chuyện đã kết thúc. ',
  notiRestartChat: 'Bắt đầu chủ đề mới trong vòng {0} giờ',
  notificationAttemptingToReconnect: 'Đang cố gắng kết nối lại...',
  notificationProcessing: 'Đang cố gắng kết nối, vui lòng chờ',
  notificationLostConnection: 'Rất tiếc, kết nối của bạn dường như bị ngắt kết nối. ',
  notificationLostConnectionCta: 'Bạn có muốn thử kết nối lại không? ',
  sydneySapphireCopyToClipboardText: 'đã sao chép vào bảng tạm. ',
  sydneySapphireUpsellContent: 'Nhận ứng dụng Bing sử dụng ai mới ngay bây giờ!',
  sydneySapphireWelcomeText: 'Chào mừng trở lại! Dưới đây là một số điều trên trang này. ',
  sydneySapphireConsentTitleText: 'Sử dụng New Bing Up Duyệt',
  sydneySapphireConsentMessageText: 'Cho phép Microsoft truy cập nội dung web trình duyệt của bạn để cá nhân hóa trải nghiệm của bạn tốt với tóm tắt do AI tạo và các tính năng điểm nóng mới của Bing. Tìm hiểu về Hơn nữa nhiều thông tin',
  sydneySapphireConsentConfirmText: 'Xác nhận',
  sydneySapphireConsentDenyText: 'từ',
  sydneySapphireSummarizeSuggestionShip: 'tóm',
  sydneySapphireExplainSuggestionShip: 'Giải thích',
  sydneySapphireKeyTakeawaysSuggestionShip: 'Điểm quan trọng',
  sydneySapphireGenerateSummaryMessage: 'Tạo tóm tắt của trang này',
  sydneySapphireGPT4Greet: 'Tốt! GPT-4 có 🎉. Trong khi sáng tạo, phản hồi có thể chậm hơn. Ý tưởng của bạn là gì?',
  typingIndicatorStopStreamingAriaLabel: 'Dừng phát trực tuyến',
  sydneyCarouselCollapse: 'gấp',
  sydneyCarouselTitle: 'Chủ đề trò chuyện gần đây',
  messageActionsCopy: 'sao',
  messageActionsCopying: 'Đang sao',
  messageActionsCopied: 'đã sao',
  messageActionsCopyError: 'lỗi',
  messageActionsReport: 'Báo',
  tooltipPositive: 'like',
  tooltipNegative: 'Không thích',
  tooltipShare: 'Chia',
  tooltipMore: 'Hơn nữa nhiều',
  tooltipSendToPhone: 'Tiếp tục trên điện thoại',
  codeDisclaimer: 'Mã này được tạo bởi AI. Xem xét và sử dụng cẩn thận. Để biết thêm thông tin, hãy {0}. ',
  codeDisclaimerLinkLabel: 'Truy cập câu hỏi thường gặp của chúng tôi',
  exportTitle: 'Xuất',
  exportTextTitle: 'Tải xuống dưới dạng văn bản (.txt)',
  exportPdfTitle: 'Tải xuống ở định dạng PDF (.pdf)',
  exportWordTitle: 'Tải xuống ở định dạng Word (.docx)',
  exportWordOnlineTitle: 'Xuất sang Word Web App',
  exportExcelTitle: 'Tải xuống ở định dạng Excel (.xlsx)',
  exportExcelOnlineTitle: 'Xuất sang Ứng dụng Web Excel',
  exportToastViewButtonLabel: 'Xem',
  exportSuccessToastTitle: 'xuất。Một số định dạng và hình ảnh có thể không xuất được. ',
  exportErrorToastTitle: 'Xuất thất bại',
  exportLoadingToastTitle: 'Đang xuất...',
  exportedFileUserTitle: 'Người',
  exportedFileBotTitle: 'Bing',
  feedbackExportButtonAriaLabel: 'Xuất',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  tooltipExport: 'Xuất',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  exportOnlineWordButtonLabel: 'Trực Word',
  exportLocalWordButtonLabel: 'Tải về',
  exportTableToExcelButtonTooltip: 'Mở trong trình duyệt',
  mobileUpsellMessage1: 'Quét mã QR này để tiếp tục cuộc trò chuyện này trên ứng dụng Bing dành cho thiết bị di động',
  mobileUpsellTitle1: 'Tiếp tục trên điện thoại',
  sydneySapphireUpsellConsentTitle: 'Có nên tiếp tục trò chuyện từ máy tính để bàn không?',
  sydneySapphireUpsellConsentMessage: 'Bạn có một cuộc trò chuyện Bing đang hoạt động trên các thiết bị khác. Bạn có muốn tiếp tục cuộc trò chuyện này không?',
  sydneySapphireUpsellConsentConfirm: 'Có',
  sydneySapphireUpsellConsentDeny: 'Không, cảm ơn',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: 'Nhấp',
  actionBarKeyboardHint: 'Đầu vào',
  feedbackShareAnswer: 'Xem câu trả lời bing này',
  feedbackShareGenerated: 'Xem những gì tôi sử dụng bing tạo ra',
  feedbackShareTitleFormat: '{0} | {1}',
  feedbackShowTonesButtonAriaLabel: 'Hiển tất cả các giai điệu',
  feedbackHideTonesButtonAriaLabel: 'ẩn tất cả các tông màu',
  feedbackHidePreciseToneButtonAriaLabel: 'ẩn chính xác',
  feedbackShareErrorToast: 'Chia sẻ thất bại。 ',
  serpfeedback: 'Phản hồi',
  shareConversation: 'Chia sẻ toàn bộ cuộc trò chuyện',
  speechAuthenticationError: 'Xác thực thất bại。 Vui lòng thử lại sau. ',
  speechUnknownError: 'Lỗi.',
  refresh: 'Làm mới',
  feedbackShareContent: 'Dưới đây là câu trả lời tôi đã tạo ra bằng cách sử dụng Bing mới (công cụ trả lời được hỗ trợ bởi AI đầu tiên trên thế giới). Nhấp để xem câu trả lời đầy đủ và yêu cầu bạn thử nó. ',
  fileUploadFlyoutInputboxAriaLabel: 'Dán URL trang web',
  fileUploadFlyoutTitle: 'Thêm tệp văn bản',
  fileUploadFlyoutUploadButtonLabel: 'Tải lên từ thiết bị này',
  fileUploadGenericErrorMessage: 'Xin lỗi - Tải lên dường như không thành công. Vui lòng thử lại',
  preview: 'Xem trước',
  toneSelectorDescription: 'Chọn kiểu hội thoại',
  toneSelectorCreative: 'sáng tạo',
  toneSelectorCreativeModifier: 'Hơn nữa',
  toneSelectorBalanced: 'Cân bằng',
  toneSelectorBalancedModifier: 'Hơn nữa',
  toneSelectorPrecise: 'Chính xác',
  toneSelectorPreciseModifier: 'Hơn nữa',
  toneSelectorMoreCreative: 'Hơn nữa\\r\\n Sáng tạo',
  toneSelectorMoreBalanced: 'Hơn nữa\\r\\n Cân bằng',
  toneSelectorMorePrecise: 'Hơn nữa\\r\\n Chính xác',
  toneSelectorFaster: 'Hơn nữa',
  toneSelectorWithGPT4: 'GPT-4',
  notificationMaxTurnsPerDay: 'Rất tiếc, bạn đã đạt đến giới hạn số tin nhắn có thể gửi tới Bing trong vòng 24 giờ. Vui lòng kiểm tra lại sau!',
  notificationMaxTurnsPerConversation: 'Xin lỗi, cuộc trò chuyện này đã đạt đến giới hạn của nó. Sử dụng nút Quét để xóa nội dung này và trò chuyện nhiều hơn với Hơn nữa. ',
  notificationMaxTurnsForMuidUsers: 'Bạn đã đạt đến giới hạn cuộc trò chuyện ngày hôm nay. ',
  notificationMaxTurnsForInPrivateUsers: 'bạn đã đạt đến giới hạn phiên inPrivate 模式。 Mở cửa sổ không inPrivate để tiếp tục trò chuyện',
  notificationUnauthorizedMuidUsersCta: 'Đăng nhập để tiếp tục trò chuyện của bạn. ',
  notificationChatEnterMuidUsers: 'Đăng nhập để đặt câu hỏi về Hơn nữa nhiều câu hỏi và thực hiện một cuộc trò chuyện dài Hơn nữa. ',
  muidUsersTermsCond1: 'Bắt đầu bằng cách nhấp vào Bắt đầu và tiếp tục tương tác với Bing, có nghĩa là bạn chấp nhận',
  muidUsersTermsCond1Inline: 'Bằng cách tiếp tục tương tác với Bing, bạn sẽ chấp nhận',
  muidUsersTermsCond2: 'và xác nhận rằng bạn đã xem',
  muidUsersPrivacyStatement: 'Tuyên bố về quyền riêng tư',
  muidUsersTermsOfUse: 'Điều khoản sử dụng',
  muidUserGetStartedText: 'Bắt đầu',
  muidUserContinueText: 'Tiếp tục',
  welcomeMobSugg1: 'Bing sử dụng AI như thế nào?',
  welcomeMobSugg2: 'Bing có thể làm gì khác? ',
  welcomeMobSugg3: 'Tin tức mới nhất trong lĩnh vực công nghệ là gì?',
  notificationResetConversation: 'Tôi xin lỗi, có vẻ như đã có lỗi. ',
  notificationResetConversationCta: 'Hãy bắt đầu lại từ đầu.',
  toneSelectorCreativeTooltip: 'Xóa cuộc trò chuyện và bắt đầu trò chuyện ban đầu và giàu trí tưởng tượng',
  toneSelectorBalancedTooltip: 'Xóa cuộc trò chuyện và bắt đầu trò chuyện giàu thông tin và thân thiện',
  toneSelectorPreciseTooltip: 'Xóa cuộc trò chuyện và bắt đầu trò chuyện ngắn gọn và thẳng thắn',
  toneSelectorSuppressedTooltip: 'Tạm không có sẵn. Vui lòng thử lại sau!',
  notificationDisengaged: 'Có lẽ đã đến lúc chuyển sang một chủ đề mới. ',
  notificationDisengagedCta: '',
  notificationForbidden: 'Rất tiếc, bạn dường như không còn có quyền truy cập vào tính năng này nữa. Vui lòng kiểm tra lại sau vài ngày. ',
  notificationTooManyRequests: 'Xin lỗi, nhu cầu bây giờ là rất lớn. Vui lòng thử lại sau. ',
  notificationUnauthorized: 'Xin lỗi, bạn dường như đã đăng xuất. ',
  notificationUnauthorizedCta: 'Vui lòng đăng nhập lại.Vui lòng đăng nhập lại.',
  notificationMessageError: 'Thông báo trước đó dường như đã bị gián đoạn. ',
  notificationSharedTip: '此 đối<strong>"{0}"</strong> đã được chia sẻ với bạn {1}',
  mmAnswerPrompt1: 'Cuối cùng tôi đã tìm thấy một cái gì đó cho bạn! Nhìn kìa. ',
  mmAnswerPrompt2: 'Cuối cùng tôi đã tìm thấy một cái gì đó! Đây có phải là những gì bạn đang tìm kiếm?',
  mmAnswerPrompt3: 'Xin lỗi vì đã nhầm lẫn, tôi đã tìm thấy một cái gì đó cho bạn. Đối với bạn!',
  mmAnswerPrompt4: 'Hey! Tôi đã tìm thấy một cái gì đó, đó có phải là những gì bạn muốn?',
  mmAnswerPrompt5: 'Nhìn! Tôi tìm thấy một cái gì đó phù hợp với bạn. ',
  mmAnswerPrompt6: 'Chờ đã, ở đây! Tôi xin lỗi vì đã làm rối tung, nhìn kìa. ',
  mmAnswerPrompt7: 'Tôi tìm thấy phương tiện truyền thông bạn muốn! Tôi xin lỗi vì đã trì hoãn nó. ',
  signInCta: 'Đăng nhập',
  signInDescription: 'để đặt ra nhiều câu hỏi của Hơn nữa và tiến hành một cuộc trò chuyện dài Hơn nữa',
  signInDescriptionInPrivate: 'Mở cửa sổ không inPrivate để thực hiện cuộc trò chuyện dài Hơn nữa hoặc đặt nhiều câu hỏi về Hơn nữa',
  copyCodeSuccessToastTitle: 'Đã sao chép vào bảng tạm',
  copyCodeButtonTooltip: 'Sao',
  copyCodeButtonSuccessTooltip: 'Đã sao',
  threadsSharedOnDate: 'Chia sẻ {0}',
  threadsMore: 'Hơn nữa nhiều',
  threadsExportPanelTitle: 'Chọn định dạng',
  threadsExportPanelAriaLabel: 'Chọn',
  threadsAADMSARedirectConfirm: 'Chuyển đổi cấu hình người dùng',
  threadsAADMSARedirectDescription: 'Bạn đang sử dụng tài khoản Microsoft của mình để lưu lịch sử hội thoại của bạn. Lần sau khi bạn đăng nhập bằng tài khoản cá nhân của bạn, nó sẽ xuất hiện ở đây. ',
  threadsCancel: 'Hủy',
  threadsChatHistory: 'Lịch sử trò chuyện',
  threadsConfirm: 'Xác nhận',
  threadsDaysAgo: '{0} ngày trước',
  threadsDefaultChatName: 'Trò chuyện không có tiêu đề',
  threadsDelete: 'xóa',
  threadsDescription: 'Trợ lý được HỖ TRỢ AI Bing hiện có thể tự động lưu cuộc trò chuyện. Bạn có thể truy cập trò chuyện từ bất kỳ thiết bị, máy tính để bàn hoặc thiết bị di động nào và tiếp tục liền mạch. ',
  threadsDescriptionNote: 'Xin lưu ý rằng tất cả các cuộc trò chuyện sẽ tự động bị xóa trong vòng 90 ngày trừ khi được lưu đặc biệt. ',
  threadsEdit: 'Đổi tên',
  threadsLoad: 'Cuộc trò chuyện',
  threadsMinimizeRecent: 'Giảm thiểu trò chuyện gần đây',
  threadsMinimizeSaved: 'Giảm thiểu các cuộc trò chuyện đã lưu',
  threadsPreview: 'Xem trước',
  threadsPreviewText: 'Nhảy trở lại trò chuyện gần đây',
  threadsRecentTitle: 'Hoạt động gần đây',
  threadsRecentTitleShort: 'Gần sử dụng',
  threadsSavedTitle: 'đã lưu',
  threadsSeeAllRecent: 'Xem tất cả các cuộc trò chuyện gần đây',
  threadsSeeAllSaved: 'Xem tất cả các cuộc trò chuyện đã lưu',
  threadsTitle: 'trò chuyện',
  threadsTitleForFlux: 'Menu',
  threadsYesterday: 'Hôm qua',
  threads2TLastAccessed: 'Thời gian trả lời cuối cùng',
  threads2TInfoChanged: 'Thông tin này có thể đã được Hơn nữa thay đổi, bởi vì',
  threads2TArchivedText: 'Ảnh chụp màn hình',
  threads2TReloadDescription: 'Nhấp vào Tải lại để hiển thị thông tin mới nhất từ web',
  threads2TFailedSearch: 'Xem Bing.com mới nhất',
  threads2TReload: 'Tìm kiếm Bing.com',
  injectedActionCardTitle: 'Trò chuyện về trang này?',
  injectedActionCardNewTopicTitle: 'Bắt đầu một cuộc trò chuyện mới về trang này?',
  injectedActionCardConfirm: 'gửi',
  injectedActionCardDeny: 'bỏ',
  webPageContextPrefix: 'đã truy cập trang web',
  useGPT4SwitchLabel: 'GPT-4',
  zeroInputSuggestionFallback1: 'Máy xay cà phê nào được đánh giá tốt nhất?',
  zeroInputSuggestionFallback2: 'Đối với một gia đình sáu người với ngân sách hạn hẹp, ba mẫu xe nào sẽ được ưu tiên hơn?',
  zeroInputSuggestionFallback3: 'Viết một câu chuyện cười mà đồng nghiệp của tôi sẽ thấy buồn cười',
  zeroInputSuggestionFallback4: 'Xu hướng tiếp theo là gì? Tôi nên mua sắm ở đâu để tìm thấy nó? ',
   zeroInputSuggestionFallback5: 'Viết một câu chuyện ngụ ngôn độc đáo về một con cá và một con ếch đang tìm kiếm tình yêu',
   zeroInputSuggestionFallback6: 'Tạo một bảng để giúp tôi lên kế hoạch cho bữa ăn trong hai tuần tới',
   zeroInputSuggestionFallback7: 'Tạo khẩu hiệu cho nền tảng truyền thông xã hội châm biếm mới',
   zeroInputSuggestionCategory1: 'Cửa hàng',
   zeroInputSuggestionCategory2: 'So sánh',
   zeroInputSuggestionCategory3: 'Cười',
   zeroInputSuggestionCategory4: 'Trò chuyện',
   zeroInputSuggestionCategory5: 'Viết',
   zeroInputSuggestionCategory6: 'Tổ chức',
   zeroInputSuggestionCategory7: 'Tạo',
   DiscoverMessageItemTitle: '📝 cùng nhau viết lại văn bản',
   DiscoverMessageItemContent: 'Thử chọn văn bản từ trang này để xem chúng ta có thể làm gì cùng nhau',
   pluginTitle: 'plugin',
   bookNowWithOpenTable: 'Đặt ngay với OpenTable',
   ScrollLeft: 'Cuộn sang trái',
   ScrollRight: 'Cuộn sang phải',
   personalizationConsentTitleText: '✨Bạn có biết rằng Bing hiện hỗ trợ personalization hóa không? ✨',
   personalizationConsentContentText1: 'Khi bạn chia sẻ sở thích của mình hoặc bất kỳ thông tin cơ bản nào bạn chọn, Bing sẽ tùy chỉnh phản hồi để bạn có thể tìm thấy chính xác những gì bạn đang tìm kiếm. Vui lòng nhấp vào bên dưới để bật tính năng mới này hoặc ',
   personalizationConsentContentText2: '. ',
   personalizationConsentLearnMoreText: 'Tìm hiểu thêm về personalization hóa',
   personalizationConsentEnableText: 'Bật',
   personalizationConsentAskAgainLaterText: 'Hỏi sau',
   personalizationConsentDisableText: 'Không, cảm ơn',
   personalizationConsentStatusPositiveText: 'personalization hóa được bật. ',
   personalizationConsentStatusNegativeText: 'personalization hóa không được kích hoạt. ',
   personalizationConsentSettingsText1: 'Để sửa đổi, vui lòng truy cập',
   personalizationConsentSettingsLinkText: 'Cài đặt trò chuyện Bing',
   personalizationConsentSettingsText2: 'Trang',
   pluginEnabledPlugin: 'đã kích hoạt',
   pluginEnabledNumber: '{0} / {1}',
   pluginStartNewTopic: 'Bắt đầu một chủ đề mới',
   pluginToChangePlugin: 'Hơn nữa sửa plu',
   pluginNotificationMaxExceeded: 'Số lượng plugin tối đa được kích hoạt',
   pluginNotificationExclusive: '{0} quá giống với {1}. Vui lòng chọn một ',
   pluginTerms: 'Điều khoản sử dụng',
   pluginPrivacy: 'Chính sách bảo mật',
   pluginPanelFreTitle: 'Plugin có sẵn ngay bây giờ',
   pluginPanelFreTextLabel: 'Mới:',
   pluginPanelFreText: 'Mở plugin để giúp bạn tìm đặt chỗ nhà hàng, chuyến bay và hơn thế nữa từ các thương hiệu yêu thích của bạn. ',
   pluginPanelFreDismiss: 'bỏ qua',
   pluginPanelAlertTitle: 'Plugin không khả dụng ở chế độ Cân bằng',
   pluginPanelAlertCta: 'Đặt lại cuộc trò chuyện',
   pluginPanelAlertSubtitle: 'và sử dụng kiểu hội thoại "Hơn nữa đa sáng tạo" hoặc "Hơn nữa chính xác" và thử lại. ',
   pluginLimitationTitle: 'Sử dụng plugin với Ai Bing',
   pluginLimitationMax: 'Chọn tối đa 3 plugin cho bất kỳ chủ đề hội thoại nào. ',
   pluginLimitationLock: 'Trước khi chọn "Chủ đề mới" để thay đổi Hơn nữa, trình cắm sẽ bị khóa vào cuộc trò chuyện. ',
   pluginShowMore: 'mở',
   pluginPanelNolimit: 'Vô hiệu hóa {0} sẽ không ảnh hưởng đến giới hạn plugin',
   threadsToggleExpansion: 'Chuyển đổi phần mở rộng',
   threadsEnabledPlugins: 'Đã kích hoạt plugin:',
   bingSearchDisabled: 'Bing**đã vô hiệu hóa**. ',
   bingSearchDisabledforMessage: 'Bing đã bị vô hiệu hóa',
   activateSearch: 'Bắt đầu một chủ đề mới và kích hoạt tìm kiếm',
   visualSearchFlyoutTitle: 'Thêm hình ảnh',
   visualSearchGenericErrorMessage: 'Xin lỗi - tải lên của bạn dường như đã thất bại. Vui lòng thử lại',
   visualSearchInvalidUrlMessage: 'Xin lỗi - URL bạn cung cấp dường như không hợp lệ. Vui lòng thử lại',
   visualSearchFlyoutInputboxAriaLabel: 'Dán hình ảnh hoặc liên kết',
   visualSearchFlyoutTakePhotoButtonLabel: 'Chụp ảnh',
   visualSearchDragAndDropLabel: 'Kéo hình ảnh đến đây',
  visualSearchFlyoutUploadButtonLabel: 'Tải lên từ thiết bị này',
  raiDisclaimerLabel: 'AI tạo ra nội dung có thể không chính xác',
  slimHeaderTitle: 'Xem câu trả lời cho Bing mới được hỗ trợ bởi AI',
  starterPageTitle: 'Bing là trợ lý trực tuyến được HỖ TRỢ AI',
  starterDescription: 'Trò chuyện với Bing bằng ngôn ngữ của riêng bạn. Nếu bạn cảm thấy bị mắc kẹt, hãy chọn một trong những lời mở đầu sau đây để xem Bing hoạt động như thế nào:',
  starterSubtitle1: 'Đối thoại',
  starterSubtitle2: 'Giải phóng sự sáng tạo của bạn',
  starterSubtitle3: 'Hơn nữa tìm kiếm thông minh',
  starterContent1: 'Bing hoạt động tốt nhất khi sử dụng các câu lệnh tự nhiên như trò chuyện hàng ngày và hỏi về nội dung tiếp theo',
  starterContent2: 'Cho dù đó là hình ảnh hoặc văn bản, Bing có thể truyền cảm hứng cho sự sáng tạo của bạn bằng cách biến tầm nhìn của bạn thành hiện thực',
  starterContent3: 'Trò chuyện với Bing là một cách tìm kiếm mới. Hãy để Bing tóm tắt nội dung web và cung cấp câu trả lời',
  starterChatQuery1: 'Bạn có nghĩ rằng có sự sống trên các hành tinh khác? Sự độc đáo của trái đất là gì? ',
  starterChatQuery2: 'Điều gì sẽ xảy ra nếu tôi gặp vấn đề với giấc ngủ nhưng chỉ xảy ra vào mùa hè?',
  starterChatQuery3: 'Tôi muốn mở một khu vườn, nhưng tôi không biết gì về nó. Bước đầu tiên là gì? ',
  starterChatQuery4: 'Bạn có nghĩ rằng cá sấu hoặc gấu xám sẽ giành chiến thắng trong cuộc chiến? ',
  starterChatQuery5: 'Gần đây tôi đã đọc rất nhiều sách không hư cấu. Bạn có thể giúp tôi tìm thấy phiên bản hư cấu của chủ đề yêu thích của tôi? ',
  starterChatQuery6: 'Hãy có một cuộc trò chuyện trong đó tất cả những gì bạn nói được viết bằng biểu tượng cảm xúc. ',
  starterChatQuery7: 'Tôi đã suy nghĩ về việc chuyển đến một nơi mới. Anh nghĩ tôi nên đi đâu? ',
  starterChatQuery8: 'Tôi đã viết nhật ký, nhưng gần đây tôi thường lười biếng. Làm thế nào tôi có thể giữ thói quen của tôi? ',
  starterChatQuery9: 'Bạn sẽ mơ như con người? Bạn sẽ mơ về điều gì? ',
  starterChatQuery10: 'Có thể xảy ra động đất, sóng thần và núi lửa phun trào cùng một lúc? ',
  starterCreateQuery1: 'Tôi có một con lông đen, ngoại trừ lông trên bụng có màu trắng. Xin vui lòng vẽ nó như một hình ảnh hoạt hình. ',
  starterCreateQuery2: 'Viết một câu chuyện trước khi đi ngủ cho cháu gái 3 tuổi của tôi. Cô ấy thích ngựa và phép thuật, và tôi nghĩ rằng câu chuyện nên được vần điệu',
  starterCreateQuery3: 'Viết một bài luận ngắn với giọng điệu của một giáo sư kiêu ngạo để chứng minh rằng mặt trăng là tốt hơn so với mặt trời Hơn',
  starterCreateQuery4: 'Vẽ một con gấu Bắc cực phơi nắng trên tảng băng trôi theo phong cách ấn tượng. Nó cũng nên uống nước chanh',
  starterCreateQuery5: 'Hãy tạo ra một màu sắc và viết một bài đăng truyền thông xã hội để giới thiệu nó với thế giới',
  starterCreateQuery6: 'Là Batman do Christian Bale thủ vai, xin vui lòng cho tôi biết làm thế nào để đối phó với giao thông bằng xe máy',
  starterCreateQuery7: 'Sản xuất một chiến dịch bán hàng cho một thương hiệu bia mới với giọng điệu của một người cha sản xuất rượu vang tại nhà và gây ra một vụ nổ nhỏ',
  starterCreateQuery8: 'Thiết kế một áp phích cho một quán cà phê với hoàng hôn và tận dụng tối đa không gian',
  starterCreateQuery9: 'Vẽ một con hươu cao cổ với tư cách là thuyền trưởng của một con tàu trên hồ',
  starterCreateQuery10: 'Viết một đoạn giới thiệu cho một bài báo về lịch sử văn học nữ quyền và cung cấp cho tôi năm lời khuyên viết để tiếp tục',
  starterCompareQuery1: 'Tìm cho tôi một công thức nấu ăn của Tiramisu, tạo cho tôi một danh sách mua sắm và sắp xếp để tôi có thể nhanh chóng tìm thấy các thành phần trong cửa hàng',
  starterCompareQuery2: 'Báo cáo tin tức địa phương hôm nay cho tôi, không bao gồm nội dung thể thao',
  starterCompareQuery3: 'Tóm tắt các nghiên cứu AI mới nhất với năm điểm chính và rút ra kết luận về xu hướng tiếp theo',
  starterCompareQuery4: 'Tạo một bảng để so sánh xe điện tốt nhất theo thương hiệu, giá cả, tính năng an toàn và các thiết bị bổ sung có thể',
  starterCompareQuery5: 'Công viên gần sân chơi trẻ em gần đây ở đâu? ',
  starterCompareQuery6: 'Có ba gợi ý rượu vang cho các món ăn Ý tôi sẽ làm vào buổi tối. Món ăn này chủ yếu là cà chua và hơi cay. ',
  starterCompareQuery7: 'Cung cấp cho tôi một bản tóm tắt các tiêu điểm mới nhất của UN',
  starterCompareQuery8: 'Tạo một bảng để so sánh những người đoạt giải Pulitzer bất ngờ và lý do của họ',
  starterCompareQuery9: 'Mô tả cách Internet hoạt động theo cách mà trẻ em có thể hiểu được',
  starterCompareQuery10: 'Dịch bài thơ "Giới thiệu thơ" sang tiếng Pháp và giải thích ngắn gọn ý nghĩa của bất kỳ tổn thất nào bằng tiếng Anh',
  notificationMaxTurnsAndOpenEdge: 'Bạn đã đạt đến giới hạn đối thoại. Để tiếp tục trò chuyện, ',
  notificationMaxTurnsAndOpenEdgeCta: 'Mở trong Microsoft Edge'
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 设置未登录用户的 codexMUIDUser 为 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Bing Chat Enterprise'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = 'AI Web Copilot'
  _w['_sydConvTranslation']['inputRaiLabel'] = 'Dữ liệu cá nhân và công ty của bạn được bảo vệ trong cuộc trò chuyện này'
}