services:
  go-proxy-bingai:
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - HEADLESS=false
      - PASS_TIMEOUT=5
    ports:
      - 8080:8080
      - 45678:45678
      - 9005:9005
